### ISSUE TITLE
Got this error on install

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdrop-pantheon#15]
After submitting the page where you create admin user, password, the checkbox for being alerted about updates, I got this error and the white screen of death:
`Call to undefined function field_attach_load() core/modules/entity/entity.controller.inc:333`

**Comment by jenlampton** [comment]
This is a known problem with the pantheon platform. You'll need to delete that site and try again. It will eventually work!

**Comment by jenlampton** [comment]
Since there's nothing we can do on our end to fix this, closing the issue...

**Comment by herbdool** [comment]
Is it this issue? https://github.com/backdrop/backdrop-issues/issues/296

**Comment by jenlampton** [comment]
That problem has been fixed @herbdool - this most recent version has only been happening on the Pantheon environment, and not consistently. I think it has something to do with which container you get when you fire up a site, and how it happened to be configured.

**Comment by jenlampton** [comment]
@quicksketch

**Comment by kreynen** [comment]
We've installed Backdrop a dozen times on Pantheon now.  There are still some issues, but this isn't one of them.
