### ISSUE TITLE
Add details about the delay of specific types of releases for Pantheon sites to README.md

### ISSUE THREAD

**Issue by kreynen** [backdrop-ops/backdrop-pantheon#28]
Today's hangout was the first I heard about a delay in some of the releases appearing in Github and Backdropcms.org and on Pantheon.  This is what we do with our install profile upstreams.  We deploy to internal hosting first, wait to see if there any bugs and then deploy the stable or bug fixed release to Pantheon.

This is not what happens with D7, D8 or WordPress.  I was expecting to see the update in the dashboard the same day, so it would be helpful to state that in https://github.com/backdrop-ops/backdrop-pantheon/blob/master/README.md

**Comment by jenlampton** [comment]
We no longer have a delay in pushing updates to Pantheon. Thanks to our new feature-freeze policy, new versions are pushed to Pantheon the day they are released for everyone else. 

I'm going to close this issue, but I would love it if a core committer could confirm. @quicksketch @herbdool @serundeputy @BWPanda
