### ISSUE TITLE
Update to 1.15.0

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/backdrop-pantheon#33]
https://github.com/backdrop/backdrop/releases/tag/1.15.0

**Comment by herbdool** [comment]
@jenlampton I created a PR for updating to 1.15.0. Or do we want to be more conservative and only go to 1.14.3?

**Comment by jenlampton** [comment]
We're ready to go to 1.15.0, but we don't usually do a PR. Can you merge the branch and then push? Put the message you want to show on the Pantheon dashboard in the merge commit message.

**Comment by herbdool** [comment]
You mean just merge directly from backdrop/backdrop:1.15.0 to backdrop-ops/backdrop-pantheon:master?

**Comment by jenlampton** [comment]
Yep, I think that's how @quicksketch does it.
