### ISSUE TITLE
Set a default temporary and public file paths

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/backdrop-pantheon#34]
From https://pantheon.io/docs/tmp#default-temporary-path, we should add something like this to settings.php:

```
/**
 * Define appropriate location for tmp directory
 */
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  $conf['file_temporary_path'] = $_SERVER['HOME'] .'/tmp';
}
```

And should do the same for public files and show how to to do it for private file directory.

**Comment by jenlampton** [comment]
I think this should be possible since 1.16.

**Comment by herbdool** [comment]
Might not need this if we do https://github.com/backdrop-ops/backdrop-pantheon/issues/58 - since it'll set the tmp path
