### ISSUE TITLE
Enforce https

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/backdrop-pantheon#35]
Pantheon now enforces https in `pantheon.upstream.yml` https://github.com/pantheon-systems/drops-7/blob/default/pantheon.upstream.yml:

```
# See https://pantheon.io/docs/pantheon-yml/#enforce-https--hsts for valid values.
enforce_https: transitional
```

We should add this since this is the default now for Pantheon upstreams. I've tested this on a site by adding to pantheon.yml and it works.

**Comment by herbdool** [comment]
It's not clear who are actually the maintainers of this project. @jenlampton? This is a pretty simple change but would still be good to have a second set of eyes.

**Comment by jenlampton** [comment]
@herbdool this repo is managed by the "Backdrop Pantheon" team, which right now is yourself, @serundeputy @quicksketch, @populist and me.

**Comment by herbdool** [comment]
@jenlampton ah thanks Jen. I forgot who was on the list.
