### ISSUE TITLE
Error deploying Backdrop site on Pantheon: add pantheon.upstream.yml.

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/backdrop-pantheon#38]
![Screenshot from 2020-06-19 15-39-51](https://user-images.githubusercontent.com/1071483/85177537-50bb5600-b24a-11ea-9ae0-e220670301c2.png)

Pantheon support suggested we try add https://github.com/pantheon-systems/drops-7/blob/default/pantheon.upstream.yml and see if that works. I think we should have that file anyway even if it doesn't fix the issue.

**Comment by herbdool** [comment]
There's a big problem with the default branch now. It is over 2 years old. With the recent renaming of branches and shuffling around, and perhaps the recent release, something got lost.

@jenlampton or @quicksketch not sure best way to fix this but can we resurrect the old branch?

**Comment by jenlampton** [comment]
@herbdool the master branch has been restored (thank you @quicksketch) I'll give a pantheon deploy a quick test...

**Comment by jenlampton** [comment]
So far so good, my new Backdrop 1.12.2 site is up and running. 
<img width="1006" alt="Screen Shot 2020-06-19 at 3 03 10 PM" src="https://user-images.githubusercontent.com/397895/85182611-0b912700-b23e-11ea-9c20-5b0d1335db4a.png">

**Comment by herbdool** [comment]
Thanks @jenlampton looks like that fixed it.
