### ISSUE TITLE
Include Pantheon dev/test/live URLs in trusted host patterns by default

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdrop-pantheon#41]
Pantheon recommends adding the following to `settings.php` so pantheon URLs for dev/test/live sites are included in `trusted_host_patterns`.  I'd like to do this in the settings.php file that is included by default for Backdrop Pantheon installs.

```php
if (defined('PANTHEON_ENVIRONMENT')) {
  if (in_array($_ENV['PANTHEON_ENVIRONMENT'], array('dev', 'test', 'live'))) {
    $settings['trusted_host_patterns'][] = "{$_ENV['PANTHEON_ENVIRONMENT']}-{$_ENV['PANTHEON_SITE_NAME']}.pantheon.io";
    $settings['trusted_host_patterns'][] = "{$_ENV['PANTHEON_ENVIRONMENT']}-{$_ENV['PANTHEON_SITE_NAME']}.pantheonsite.io";
  }
}
```

**Comment by jenlampton** [comment]
PR filed at https://github.com/backdrop-ops/backdrop-pantheon/pull/42, would love a review!

**Comment by herbdool** [comment]
Looks good to me.
