### ISSUE TITLE
Update Pantheon Upstream to 1.18.2

### ISSUE THREAD

**Issue by Steve-A-Orr** [backdrop-ops/backdrop-pantheon#48]
Now considering whether I can use Backdrop in two projects. Would like to have thePantheon “upstream” updated to the version put out two days ago, but don’t know the process or time-lag after new versions are published.

**Comment by herbdool** [comment]
Should be available today.

**Comment by Steve-A-Orr** [comment]
Fantastic. For posterity, do we think this update will reliably happen within a week of the release of a new version or is it more dependent on a person’s availability?

**Comment by herbdool** [comment]
The aim is to create it with in a week. If it's a security update than
immediately.

**Comment by Steve-A-Orr** [comment]
Thank you for your answers, time and efforts.
