### ISSUE TITLE
Properly set Pantheon environment variables: $_SERVER['BACKDROP_SETTINGS']['settings'] should be set instead of $_SERVER['BACKDROP_SETTINGS']['conf']

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/backdrop-pantheon#58]
$_SERVER['BACKDROP_SETTINGS'] is set from $_SERVER['PRESSFLOW_SETTINGS'] but that is the old d7 variable. There's https://github.com/backdrop/backdrop/pull/60 which added support for this.

Without this, we can't use `settings_get()`. With this it makes it easier to port `pantheon_apachesolr` module from drop7.

**Comment by eric2pin** [comment]
@herbdool Happy to help but could use more direction on _how_ to help. Are you just trying to make sure that your changes to settings.php and the way $_SERVER['BACKDROP_SETTINGS'] is set, which help with the pantheon_apachesolr port, still works as expected with the Pantheon env?

**Comment by herbdool** [comment]
@eric2pin there were a few changes to settings to be made so I figured it would be better to put the separate PRs together into one branch https://github.com/backdrop-ops/backdrop-pantheon/pull/64 and then merge that into master. That will reduce the number of updates downstream people have to deal with. In the PR it links to which issues are addressed.

Note that I've proposed the creation of settings.pantheon.php to match drop8 file of the same name: https://github.com/pantheon-systems/drops-8/blob/default/sites/default/settings.pantheon.php.

**Comment by herbdool** [comment]
I spun up a new site using the Backdrop Pantheon upstream too and when I look at `$ENV` I see `HASH_SALT` but not `DRUPAL_HASH_SALT` (unlike in drop9 where it does seem to exist). It's odd that you're seeing the opposite.

There is a `drupal_hash_salt` in `$_SERVER['BACKDROP_SETTINGS']`. 

Just to be sure I made sure to create the site by going to [backdropcms.org/demo](https://backdropcms.org/try-backdrop)

**Comment by eric2pin** [comment]
You're correct, when I spin up from the Backdrop CMS upstream link, I get the salt in the HASH_SALT index. The sites I used as a base to test are a custom upstream (Backdrop CMS upstream + our custom code) and we probably selected "Drupal" as the framework somewhere along the way in Pantheon's custom upstream setup.

**Comment by eric2pin** [comment]
Yes, what I'm seeing is $_ENV['DRUPAL_HASH_SALT']. Hard to say -- we're almost certainly an edge case but Pantheon itself for Backdrop CMS is in edge case territory as far as I know. It's super easy to check for both -- maybe until Pantheon has its own option for Backdrop CMS out-of-the-box it doesn't hurt to cover both options.

**Comment by herbdool** [comment]
Thanks @eric2pin I've updated it so it checks for both. Let me know if you notice anything else. Otherwise I think it's ready to merge.
