### ISSUE TITLE
Bump MariaDB Version to 10.4

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdrop-pantheon#68]
There's a long-threaded issue about a Pantheon-specific upgrade problem when moving from D7 to Backdrop at https://github.com/backdrop/backdrop-issues/issues/5496. It seems to be fundamentally caused by MariaDB on Pantheon being out of date. Using the Backdrop upstream currently defaults to MariaDB 10.0.23, which was released Dec 18, 2015. This 8 year old version of MariaDB seems to not support upgrading from Drupal 7 or UTF8-MB4 support (emoji support). We should bump the version to at least MariaDB 10.3.

https://pantheon.io/docs/pantheon-yml#specify-a-version-of-mariadb

**Comment by klonos** [comment]
PR to bump it to 10.4 (which is what the Drupal upstream is using as well): https://github.com/backdrop-ops/backdrop-pantheon/pull/70

**Comment by laryn** [comment]
Looks good to me!

**Comment by klonos** [comment]
@laryn @quicksketch can someone please merge this then?

**Comment by jenlampton** [comment]
I'm going to update the mysql version via pantheon.yml for one or two of my Backdrop sites and see what happens. 🤞

**Comment by jenlampton** [comment]
Well, I updated my pantheon.yml, but it didn't seem to do anything?  

The comnand line said to check the workflows via the dashboard:
<img width="910" alt="Screen Shot 2023-02-16 at 1 41 13 PM" src="https://user-images.githubusercontent.com/397895/219493337-dfe20e90-6c6d-4710-a621-e2a6d09e58f2.png">
The workflows said it was done:
<img width="866" alt="Screen Shot 2023-02-16 at 1 40 13 PM" src="https://user-images.githubusercontent.com/397895/219493370-a1dcb127-a37c-49e4-860c-06b5b4828963.png">
But the status report still reports version 5.5.30 
<img width="1197" alt="Screen Shot 2023-02-16 at 1 40 36 PM" src="https://user-images.githubusercontent.com/397895/219493380-503a2ee3-208f-4e42-8ca0-c81ea03eb159.png">

**Comment by jenlampton** [comment]
Pantheon is reporting that the databse version has been updated, but that the status report isn't able to tell. We are using the following to get the version information:

```
Database::getConnection()->version()
```
This is somehow returning the wrong information.

**Comment by klonos** [comment]
Pinging @laryn and @herbdool ...can we please merge this and make sure that this version is what's being used in new Backdrop installation on Pantheon?

**Comment by laryn** [comment]
Thanks @klonos, @quicksketch, and @jenlampton -- merged!
