### ISSUE TITLE
Push version 1.26.2 to Pantheon?

### ISSUE THREAD

**Issue by Steve-A-Orr** [backdrop-ops/backdrop-pantheon#71]
As you know, Drupal 7.99 came out a bit ago and Backdrop 1.26.2 was released a little after that. Although I see I can upgrade from within the Backdrop administrative GUI, I still thought that waiting for an upstream release from within the Pantheon environment was preferable.

Is this still true and, if so, do you already have an estimated time that this will come out?

**Comment by laryn** [comment]
Yes, that's true. This slipped off my radar -- my apologies! I'll see if I can get that taken care of today.

**Comment by laryn** [comment]
@Steve-A-Orr This should be there for you!
