### ISSUE TITLE
Error related to CKEDITOR when applying Upstream 1.27.1 

### ISSUE THREAD

**Issue by Steve-A-Orr** [backdrop-ops/backdrop-pantheon#72]
I have two different development sites in Pantheon. I applied the Upstream update on one with no problem and the second is giving me a generic "something went wrong when applying updates" error.

Pantheon states they could only find this in their logs:

`[409] ["CONFLICT (modify/delete): core/modules/ckeditor/ckeditor.api.php deleted in HEAD and modified in upstream/master. Version upstream/master of core/modules/ckeditor/ckeditor.api.php left in tree."]`

Seems the code difference between my two sites is that in one I took the steps to manually remove the CKeditor (4) files and directory and in the other I did not. The log entry seems to support that this causes the error. 

I looked at the [Backdrop 1.27.1 release notes](https://github.com/backdrop/backdrop/releases/tag/1.27.1) and do not see that any changes regarding CKeditor were mentioned. Do you think this was only added in the Pantheon Upstream version or maybe it just wasn't documented in the release notes?

Would you suggest that I manually add back the **ckeditor.api.php** in order to get the update to conclude or do you think it is more involved?

**Comment by Steve-A-Orr** [comment]
I found a backup that was potentially taken before my actions to remove the CKeditor 4 files. I will restore to it and then attempt another Upstream update.

**Comment by Steve-A-Orr** [comment]
That was a backup taken previous to my updating to 1.27.0, so I was left with two Upstream updates to apply. Since it was also before I removed the CKeditor 4 directory, which I think was discussed as an option but cannot find the thread, it worked. I've left this open for you all to respond, if desired. Feel free to close it as my issue is resolved.

**Comment by laryn** [comment]
@Steve-A-Orr Sorry for the delayed response but I'm glad you solved it. The CKE4 files will be removed from core at some point but not yet -- in the meantime you can disable/uninstall CKE4 on your sites but don't worry about removing the CKE4 directory manually.
